### ISSUE TITLE
How am I supposed to add/edit levels? Or characters?

### ISSUE THREAD

**Issue by Souhail-Bel** [coreh/WebSonic#7]
So far, I didn't find anyway to make levels for this Engine or modify the actual one.

Is there any tool that could be used for this purpose? To make levels and edit them?

I also want to change Sonic into other models that I have...

Should I write it all or is there an online tool?

**Comment by alexandlazaris** [comment]
@Loom-Souhail-Mexatron  I've had a go at adding basic level editing guide if you're still interested:

https://github.com/coreh-deprecated/WebSonic/pull/9

If you imagine a top down level as being tile based, then it's do-able. Though it is not the most friendliest dev experience to edit a level as you can get lost in json arrays. 

The request to make a level editor is still open so feel free to give that a crack too 👍

**Comment by Souhail-Bel** [comment]
> @Loom-Souhail-Mexatron  I've had a go at adding basic level editing guide if you're still interested:
> 
> https://github.com/coreh-deprecated/WebSonic/pull/9
> 
> If you imagine a top down level as being tile based, then it's do-able. Though it is not the most friendliest dev experience to edit a level as you can get lost in json arrays. 
> 
> The request to make a level editor is still open so feel free to give that a crack too 👍 

Thank you so much.
I recall wasting so much time trying to decipher what was actually happening.

That basic level editing guide you added is what I just needed.

**Comment by alexandlazaris** [comment]
no problem @Loom-Souhail-Mexatron . I'm still interested and curious about this engine. My appreciation/love for Sonic is high, and am happy to help this project pick up steam again.

Not sure what to do about the open PR though, as the owner has marked their OG account as 'deprecated'. Might need to fork it and start anew. Open to ideas
